SELECT * FROM users;
SELECT * FROM USERS WHERE ID = 2;
UPDATE `users`SET`FIRST_NAME`= 'Claudio' WHERE `id` = '2';
INSERT INTO USERS(FIRST_NAME, LAST_NAME) VALUES ('Carina','Orellana');
DELETE from USERS WHERE ID = 7;

